---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: install
  ansible.builtin.include_tasks: install.yml

- name: chroot
  ansible.builtin.include_tasks: chroot.yml
  when:
    - unbound_chroot_dir is defined
    - unbound_chroot_dir | string | length > 0

- name: configure
  ansible.builtin.include_tasks: configure.yml

- name: service
  ansible.builtin.include_tasks: service.yml
