---

- name: disable systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false
  when:
    - ansible_service_mgr == 'systemd'

- name: enable unbound service
  ansible.builtin.service:
    name: unbound
    enabled: true
    state: started

