---

- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''

  vars:

    unbound_config:
      server:
        verbosity: 1
        statistics-interval: 240
        use-syslog: "no"
        log-queries: "yes"
        logfile: /var/log/unbound.log
        num-threads: 3

        interface: 0.0.0.0
        # interface: ::0
        do-ip4: 'yes'
        do-ip6: 'no'
        do-udp: 'yes'
        do-tcp: 'yes'
        # do-daemonize: no
        # access-control: 0.0.0.0/0 allow
        # access-control: 10.0.0.0/8 allow
        # access-control: 172.16.0.0/12 allow
        access-control:
          - '127.0.0.0/8 allow'
          - '172.16.0.0/12 allow'
          - '192.168.0.0/16 allow'
          - 'fc00::/7 allow'
          - 'fe80::/10 allow'
        #access-control: 192.168.0.0/16 allow
        #access-control: fc00::/7 allow
        #access-control: fe80::/10 allow
        # access-control: ::0/0 allow
        directory: "/etc/unbound"
        # username: unbound
        # auto-trust-anchor-file: trusted-key.key
        # private-address: 10.0.0.0/8
        # private-address: 172.16.0.0/12
        # private-address: 192.168.0.0/16
        # private-address: 169.254.0.0/16
        # private-address: fc00::/7
        # private-address: fe80::/10
        local-zone:
          - '"doubleclick.net" redirect'
        local-data:
          - '"doubleclick.net A 127.0.0.1"'


        # cache-min-ttl needs to be less or equal to cache-max-negative-ttl
        cache-min-ttl: 5
        cache-max-negative-ttl: 60
        root-hints: "/etc/unbound/root.hints"
        hide-identity: 'yes'
        hide-version: 'yes'
        prefetch: 'yes'
        max-udp-size: 4096
        msg-buffer-size: 65552
        unwanted-reply-threshold: 10000
        ipsecmod-enabled: 'no'

      forward_zone:
        name: "."
        # definitely censor free & log free with DNSSEC Support:
        forward_addrs:
          - 84.200.69.80   # DNS Watch
          - 84.200.70.40   # DNS Watch
          - 77.109.148.136 # Xiala.net
          - 77.109.148.137 # Xiala.net
          - 91.239.100.100 # censurfridns.dk
          - 89.233.43.71   # censurfridns.dk
        # forward-addr: 84.200.70.40   # DNS Watch
        # forward-addr: 77.109.148.136 # Xiala.net
        # forward-addr: 77.109.148.137 # Xiala.net
        # forward-addr: 91.239.100.100 # censurfridns.dk
        # forward-addr: 89.233.43.71   # censurfridns.dk

      remote_control:
        control-enable: 'yes'
        control-interface: 127.0.0.1
        control-port: 8953
        server-key-file: "/etc/unbound/unbound_server.key"
        server-cert-file: "/etc/unbound/unbound_server.pem"
        control-key-file: "/etc/unbound/unbound_control.key"
        control-cert-file: "/etc/unbound/unbound_control.pem"

      # cachedb:
      #   # backend: "testframe"
      #   # secret seed string to calculate hashed keys
      #   secret-seed: "default"
      #   # For "redis" backend:
      #   # redis server's IP address or host name
      #   redis-server-host: 127.0.0.1
      #   # redis server's TCP port
      #   redis-server-port: 6379
      #   # timeout (in ms) for communication with the redis server
      #   redis-timeout: 100

  roles:
    - role: ansible-unbound
